// <auto-generated />
using EletroCheck.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EletroCheck.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230422020320_Migracao_Primeira")]
    partial class Migracao_Primeira
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EletroCheck.Models.Pessoa", b =>
                {
                    b.Property<string>("CpfId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("CpfId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("EletroCheck.Models.Usuario", b =>
                {
                    b.Property<string>("emailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<string>("CpfId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.HasKey("emailId");

                    b.HasIndex("CpfId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EletroCheck.Models.Usuario", b =>
                {
                    b.HasOne("EletroCheck.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("CpfId");

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
